;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-slash
        electric-newline-and-maybe-indent
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        insert-parentheses
        xterm-paste
        ))
